curl 'https://jsjsl.lexiangla.com/api/v1/points/check-in' \
  -X 'POST' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"' \
  -H 'X-XSRF-TOKEN: a6MBea3rZtk%2BfpJ5I2MGGsYtdwVwMBoix%2F5DxrgEayK2EUkaSUC42Rue%2Bn0s7GXuIR2P5nNFri5NzblWG%2FvWkHSyhP%2FVBZwLKT6is%2BF5Rsk%3D' \
  -H 'X-Auth-Type: api' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer: https://jsjsl.lexiangla.com/notifications?company_from=jsjsl' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --compressed
