## jslsign.yml
name: 'jslsign'
 
on:
  push:
  schedule:
    - cron: '30 7 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
      - name: 'Run sign.sh' # 步骤二，执行sh命令文件
        run: bash sign.sh && node publish-question.js
