## jslsign.yml
name: 'jslsign'
 
on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    strategy:
     matrix:
       node-version: [18.4.0]
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
           node-version: '18.4.0'
      - name: 'Run sign.sh' # 步骤二，执行sh命令文件
        run: bash sign.sh && node publish-question.js
